# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fake Store' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fake Store

  target 'Fake StoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Fake StoreUITests' do
    # Pods for testing
  end

end
